### ISSUE TITLE
Rebuild PHP code with comments

### ISSUE THREAD

**Issue by ichiriac** [chris-l/php-unparser#1]
Hi @chris-l 

I would like to use your unparser to generate php code for this project : https://github.com/ichiriac/pdoMap and I would like to also support comment blocks.

I've releases php-parser under 0.1.4 and it's now handling comment blocks :
https://github.com/glayzzle/php-parser/blob/master/src/parser/comment.js

But be aware, into the class body, comments decorate properties, constants, and methods : https://github.com/glayzzle/php-parser/blob/master/src/parser/class.js#L135

**Comment by chris-l** [comment]
Hi!

Do I need to do something special in order to get the comments?

I tried to parse
```
//a comment
echo 10;
```

But I only got 
```
[
  "program",
  [
    [
      "sys",
      "echo",
      [
        [
          "number",
          "10"
        ]
      ]
    ]
  ]
]
```

**Comment by ichiriac** [comment]
Hi @chris-l 

Yes, you have to enable documentation :
https://github.com/glayzzle/php-unparser/blob/master/test/index.js#L44

I've started to make some changes here : https://github.com/chris-l/php-unparser/pull/2

Don't merge the pull-request, remains many change to be done.

**Comment by chris-l** [comment]
Oh wow, thanks for your collaboration!
What if instead of being one huge pull request with all the changes, it were several PRs,  each handling a different thing?

Like one adding support for the comments, other with the changes to const, semicolons and other small fixes, and another one with the magento thing? (and btw I'm not sure about that last one - what it does?)

**Comment by ichiriac** [comment]
The magento part is just for testing purpose - if the project is able to rebuild all sources from a project like magento or sf2 or zf2 ... it should cover at least 70% of the PHP language including some edge cases.

It will be hard to separate commits so I will not be able to make various pull requests.

Actually it's rebuilding well comments, but for that you need to use the master version of php-parser (future 0.1.5 not yet released) so you could merge this pull request

Once done, I'll start the travis/coverall config and send you a pull request, 

After I will finish to cover Magento2 and maybe others to be sure that majority of the code is covered well

**Comment by chris-l** [comment]
Well it's ok, I did the separation of commits. Check my comments on your PR #2
It seems like there is a problem with adding comments on properties of a class. I'll check that later.
