### ISSUE TITLE
Improve tests in order to validate resulting code

### ISSUE THREAD

**Issue by ichiriac** [chris-l/php-unparser#13]
As explained here : https://github.com/chris-l/php-unparser/pull/12#issuecomment-352189488

Tests are actually just testing that the library executes writers, but does not check output.

One thing could make the test more robust, I should do something like this :
- parse a file
- unparse a file
- parse again the unparser code
- test matching around both codes
(maybe ignore comments from initial parsing in order to avoid edge case problems)

**Comment by Sevavietl** [comment]
I will try to implement some unit tests and will make PR, if you do not mind.

Will try to do this during next week.

**Comment by chris-l** [comment]
Hehe, of course I don't mind ;)

I will also try to implement a test like @ichiriac is purposing.

**Comment by Sevavietl** [comment]
Hi.

Do you mind if I use jest for unit testing?

And the most simple test for interface, for example, will be like this:
```

var CodeGen = require('../node_translators');
var parser = require('php-parser');

describe('Interface', function () {
  var codeGen = new CodeGen({});

  test('translates ast of simple interface', function () {
    var phpInterfaceCode = 'interface Foo\n{\n}\n';
    var ast = parser.parseEval(phpInterfaceCode).children.shift();

    expect(codeGen.interface(ast, '')).toBe(phpInterfaceCode);
  });
});
```

If it is OK and you don't mind using jest, I will try to cover some more stuff with such test.

**Comment by ichiriac** [comment]
Hi @Sevavietl,

I never used jest before but I'm ok with it, it seems a great testing framework and the declarative syntax is clean.

Do you had already used mocha and should for testing ? I'm actually using them and I start to know the assertions methods so it would be easier for me to write tests.

Anyway, if you prefer Jest for it's feature or else I'm with you :+1:

**Comment by chris-l** [comment]
Hi! Sorry for the late answer, I been busy for the holidays!

Ok, about Jest. I have never used it either, normally I use Jasmine. (and to a lesser degree, mocha)
As far as I have seen, all this libraries look similar (They have pretty much the same syntax: mocha, jest and jasmine use `describe` and `it`. And the `assert.equal` of mocha is similar to the `expect`/`toBe` of jasmine and jest).

So, in general I'm not against with using Jest. Having said that, is there a nice feature that Jest has over mocha or jasmine?

**Comment by chris-l** [comment]
Well, sorry for the time. But I finally added some tests! Right now, they are only a few, but I will add more tests (hopefully, pretty soon).

And since I am more familiar with jasmine, I decided to use that.
(The existent test was converted to use jasmine too, by the way)
