### ISSUE TITLE
Multiline comment will be mistakenly transformed into single line

### ISSUE THREAD

**Issue by zsxsoft** [chris-l/php-unparser#14]
According to ASTExplorer, https://astexplorer.net/#/gist/c5098fd3b19f3c0da9de29986aa553d9/578cf3e85d8b5e4aee923e3fa3a24e9de93def19 , the parser worked as expected.

Code here:
```php
/*
aa
aa
aa
cc
*/
```
![image](https://user-images.githubusercontent.com/2398785/34413068-f11c4ebc-ec1b-11e7-9e7b-e4e4625eae90.png)

**Comment by zsxsoft** [comment]
https://github.com/glayzzle/php-parser/issues/88

**Comment by ichiriac** [comment]
Hi @zsxsoft,

I'm currently working on a 3.0 release of the parser and comments nodes will be changed in order to be more consistent, actually it's a bit obscure on this kind of code :

````
/**
 * Line 1
 * Line 2
 */
// LINE 1
/* LINE 2 
LINE 2 !..
*/
# LINE 3
````

After this release I'll send a PR here in order to  be compliant with the new release.

**Comment by chris-l** [comment]
Ok, it seems to be working fine now. I'm not sure if the parser should set `node.isDoc = true` for any multiline comment, but right now, the unparser detects that case and set it as `isDoc = true`.
