### ISSUE TITLE
dangerous process.exit

### ISSUE THREAD

**Issue by huashiyiqike** [chris-l/php-unparser#3]
in NPM version 0.1.3, php-unparser/node_translators/index.js has a process.exit(), which is quite dangerous. Could you change it to exceptions as in github version?

**Comment by chris-l** [comment]
Oh!
Ok, I published a version 0.1.4 that point before the commits related to comments  (since that part is not done yet)

You can see the repo at that version [here](https://github.com/chris-l/php-unparser/tree/version0.1.4)

I will delete that branch once the next main version is done.
